# Conexion a Oracle 18c XE
# Esquema: RESIDENCIAL  |  Tablespace: RESIDENCIAL_TBS  |  Service: xepdb1
#
# IMPORTANTE: este archivo NO debe commitearse con credenciales reales.
# Agrega src/main/resources/bd.properties a .gitignore.

db.url=jdbc:oracle:thin:@localhost:1521/xepdb1
db.usuario=RESIDENCIAL
db.clave=Residencial2024#
